@extends('layouts.master')
@section('style')
@endsection
@section('content')
    @include('slider')
    @include('special-offers')
    @include('brands')
    @include('most-viewed-products')
    @if(isset($lastVisitedProducts))
        @include('just-arrived')
    @endif
@endsection
@section('script')
@endsection
